name: Deploy to Scaleway

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.VPS_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            set -e

            IMAGE=rg.nl-ams.scw.cloud/skybluelab/ocean:latest

            # 1. Login to registry
            echo "${{ secrets.SCW_SECRET_KEY }}" | sudo docker login rg.nl-ams.scw.cloud -u nologin --password-stdin

            # 2. Pull latest image
            sudo docker pull $IMAGE

            # 3. Stop + remove old container (if it exists)
            sudo docker stop skyblue-app || true
            sudo docker rm skyblue-app || true

            # 4. Run new container
            sudo docker run -d \
              --name skyblue-app \
              -p 80:8080 \
              -v /model_weights_tokeniser:/data \
              $IMAGE

            # 5. Cleanup unused images
            sudo docker image prune -af